name: mm
channels:
  - conda-forge
dependencies:
  - copernicusmarine=1.3.3
  - intake-xarray=0.7.0
  - intake=2.0.6
  - loguru=0.7.2
  - plotly=5.24.0
  - pyinterp=2024.6.0
  - python=3.11
  - s3fs=2024.6.1
  - xarray=2024.7.0
  - xesmf=0.8.7
  - yaml=0.2.5
  - zarr=2.18.2
  - cattrs=24.1.2
  - arrow=1.3.0
  - pip:
      - blosc==1.11.2
      - dbdreader==0.5.8
      - gliderflight==1.2.0
      - gsw==3.6.19
      # The below are installed from local sources cloned from NOC gitlab
      #- latlon
      #- mamma-mia
      #- glidernetcdf